Repository PayKids-Compose/paykids-android-compose, pull requests merged in 2025-07, with the labels that each got.

#58 feat: 스플래시 액티비티 / refactor: 내비게이션 실행만 되도록 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/paykidscompose/app/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
Labels: feature, refactor

#63 refactor: 퀴즈, 학습하기 화면 컴포저블 분리
  presentation/src/main/java/com/paykidscompose/presentation/model/type/QuizResultType.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/section/ImageQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/section/QuizTopBar.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/section/ShortAnswerQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/section/TextChoiceQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/StudyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/ChatBubble.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/ChatInput.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/StageInfoBox.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/StudyTopBar.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/state/QuizResultState.kt
Labels: refactor

#64 refactor: 현재 루트를 문자열로 받아오는 거에 맞게 전체적으로 수정.
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/bottom/BottomBarItem.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/NavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/AppBottomBarComponents.kt
Labels: refactor

#68 refactor: 퀴즈클리어 화면에서 홈으로 이동했을 때 백스택에 남아서 홈에서 뒤로가기 하면 앱이 종료 안되는 것을 수정.
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
Labels: refactor

#67 feat: 퀴즈 전환 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyQuiz.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizEntryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/StudyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/ChatBubble.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/ChatInput.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/section/StageInfoBox.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#75 feat: common에 추상 클래스 모델와 매퍼 추가
  common/src/main/java/com/paykidscompose/common/model/Model.kt
  common/src/main/java/com/paykidscompose/common/model/ModelMapper.kt
Labels: feature

#77 refactor: 마이페이지 수정 및 뷰모델 추가.
  presentation/src/main/java/com/paykidscompose/presentation/base/UIState.kt
  presentation/src/main/java/com/paykidscompose/presentation/base/ViewState.kt
  presentation/src/main/java/com/paykidscompose/presentation/exception/AppException.kt
  presentation/src/main/java/com/paykidscompose/presentation/exception/ExceptionType.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/MyPageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/UIStateComponents.kt
Labels: feature, refactor

#79 refactor: 퀴즈 화면 UIState 사용
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizViewModel.kt
Labels: refactor

#80 refactor: 용돈일기 화면 수정 및 뷰모델 추가
  presentation/src/main/java/com/paykidscompose/presentation/model/AllowanceDiaryUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryViewModel.kt
Labels: feature, refactor

#82 refactor: 용돈일기 분석 화면 수정
  presentation/src/main/java/com/paykidscompose/presentation/model/ExpenseAnalysisUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor

#83 refactor: 학습하기 화면 stageNumber 파라미터 추가
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/QuizNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/StudyScreen.kt
Labels: refactor

#84 feat: data 모듈 DTO 작성
  data/build.gradle.kts
  data/src/main/java/com/paykidscompose/data/model/BaseListResponse.kt
  data/src/main/java/com/paykidscompose/data/model/BaseResponse.kt
  data/src/main/java/com/paykidscompose/data/model/allowance/AllowanceChartAmountDTO.kt
  data/src/main/java/com/paykidscompose/data/model/allowance/AllowanceChartCategoryDTO.kt
  data/src/main/java/com/paykidscompose/data/model/allowance/AllowanceChartDTO.kt
  data/src/main/java/com/paykidscompose/data/model/allowance/CategoryDTO.kt
  data/src/main/java/com/paykidscompose/data/model/quest_achivement/AchievementDTO.kt
  data/src/main/java/com/paykidscompose/data/model/quest_achivement/QuestDTO.kt
  data/src/main/java/com/paykidscompose/data/model/quiz/QuizClearedDTO.kt
  data/src/main/java/com/paykidscompose/data/model/quiz/QuizDTO.kt
  data/src/main/java/com/paykidscompose/data/model/user/LoginDTO.kt
  data/src/main/java/com/paykidscompose/data/model/user/UserDTO.kt
  gradle/libs.versions.toml
Labels: feature

#85 fix: 홈 화면 툴팁 오프셋 수정
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TooltipComponents.kt
Labels: fix

#88 refactor: 용돈일기 분석 화면 수정
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
Labels: refactor

#89 refactor: 홈 화면 스크롤, 스테이지, 툴팁 개선
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/constants/HomeScreenConstants.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TooltipComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/util/StageVisualUtil.kt
Labels: feature, refactor, fix

#92 feat: api 관련 코드 추가 apiservice 및 리포지토리들을 추가했습니다.
  data/build.gradle.kts
  data/src/main/java/com/paykidscompose/data/database/PayKidsPreference.kt
  data/src/main/java/com/paykidscompose/data/network/NetworkAuthenticator.kt
  data/src/main/java/com/paykidscompose/data/network/NetworkInterceptor.kt
  data/src/main/java/com/paykidscompose/data/network/NetworkModule.kt
  data/src/main/java/com/paykidscompose/data/network/service/AuthApiService.kt
  data/src/main/java/com/paykidscompose/data/network/service/ExpenseAllowanceApiService.kt
  data/src/main/java/com/paykidscompose/data/network/service/ExpenseCategoryApiService.kt
  data/src/main/java/com/paykidscompose/data/network/service/IncomeAllowanceApiService.kt
  data/src/main/java/com/paykidscompose/data/network/service/IncomeCategoryApiService.kt
  data/src/main/java/com/paykidscompose/data/network/service/UserApiService.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/ExpenseAllowanceRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/ExpenseCategoryRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/IncomeAllowanceRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/IncomeCategoryRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/UserRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/util/Constants.kt
  gradle/libs.versions.toml
Labels: feature

#95 feat: 학습하기 채팅 Network 관련 코드 작성
  data/src/main/java/com/paykidscompose/data/model/study/ChatResponseDTO.kt
  data/src/main/java/com/paykidscompose/data/network/NetworkModule.kt
  data/src/main/java/com/paykidscompose/data/network/service/ChatApiService.kt
  data/src/main/java/com/paykidscompose/data/repositories/ChatRepositoryImpl.kt
Labels: feature

#96 feat: 카카오 로그인, 로그아웃 구현
  data/build.gradle.kts
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/paykidscompose/data/model/Token.kt
  data/src/main/java/com/paykidscompose/data/network/service/authentication/KakaoLoginHelperActivity.kt
  data/src/main/java/com/paykidscompose/data/network/service/authentication/KakaoLoginService.kt
  data/src/main/java/com/paykidscompose/data/network/service/authentication/SocialLoginService.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/util/Extensions.kt
Labels: feature

#97 feat: 퀘스트 페이지 UI 구현
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyQuest.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/bottom/BottomBarItem.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/TabNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quest/QuestAchievementsScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quest/QuestAndAchievementScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quest/QuestAndAchievementTab.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quest/page/AchievementPage.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quest/page/QuestPage.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#108 feat: 의존성 수동 주입 코드 추가.
  app/src/main/java/com/paykidscompose/app/PayKidsApplication.kt
  app/src/main/java/com/paykidscompose/app/SplashActivity.kt
  app/src/main/java/com/paykidscompose/app/di/ApplicationContainerImpl.kt
  common/src/main/java/com/paykidscompose/common/di/ApplicationContainer.kt
  common/src/main/java/com/paykidscompose/common/di/ApplicationContainerProvider.kt
  common/src/main/java/com/paykidscompose/common/usecase/user/SaveNicknameUseCase.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/LoginNicknameViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/LoginViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/MyInfoViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/MyPageViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNicknameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNicknameViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoViewModel.kt
Labels: feature, refactor

#111 refactor: QuizMapper QuizType 매핑
  app/build.gradle.kts
  common/build.gradle.kts
  common/src/main/java/com/paykidscompose/common/enums/QuizClearType.kt
  common/src/main/java/com/paykidscompose/common/enums/QuizType.kt
  common/src/main/java/com/paykidscompose/common/model/QuizModel.kt
  data/build.gradle.kts
  data/src/main/java/com/paykidscompose/data/mapper/quiz/QuizMapper.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyQuiz.kt
  presentation/src/main/java/com/paykidscompose/presentation/mapper/quiz/QuizUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizClearConfigUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/type/QuizType.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/QuizNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizClearScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/section/ShortAnswerQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
Labels: refactor, chore

#113 fix: Login 버그 수정
  common/src/main/java/com/paykidscompose/common/usecase/authentication/LoginUseCase.kt
  data/src/main/java/com/paykidscompose/data/model/TokenManagerImpl.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/LoginScreen.kt
Labels: fix

#116 refactor: 리포지토리에서 로그아웃 하면 프리퍼런스 전부 삭제하도록 수정했습니다.
  common/src/main/java/com/paykidscompose/common/usecase/authentication/CheckUserCompletionStatusUseCase.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DividerComponents.kt
Labels: refactor

#117 refactor: 파일, 클래스 명 수정 및 문자열을 상수로 수정, ManagerImpl은 리스너 2개로 변경
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  app/src/main/java/com/paykidscompose/app/SplashActivity.kt
  common/src/main/java/com/paykidscompose/common/model/AuthStatusManager.kt
  common/src/main/java/com/paykidscompose/common/usecase/authentication/CheckUserCompletionStatusUseCase.kt
  data/src/main/java/com/paykidscompose/data/model/AuthStatusManagerImpl.kt
  data/src/main/java/com/paykidscompose/data/model/TokenManagerImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/UserRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/util/Constants.kt
Labels: bug, refactor

#118 refactor: 매니저의 리스너 변수
  data/src/main/java/com/paykidscompose/data/model/AuthStatusManagerImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/UserRepositoryImpl.kt
Labels: refactor

#119 feat: HomeViewModel 작성 및 의존성 수동 주입
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  app/src/main/java/com/paykidscompose/app/di/ApplicationContainerImpl.kt
  common/src/main/java/com/paykidscompose/common/di/ApplicationContainer.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/HomeViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeViewModel.kt
Labels: feature

#121 fix: dp를 0.5로 하면 몇 개가 한 번씩 안 보이는 버그가 있어서 1로 수정합니다.
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DividerComponents.kt
Labels: bug, fix

#122 feat: 마이페이지 화면
  common/src/main/java/com/paykidscompose/common/enums/ExceptionType.kt
  common/src/main/java/com/paykidscompose/common/exception/PayKidsException.kt
  common/src/main/java/com/paykidscompose/common/model/Dialog.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
Labels: feature, refactor

#124 feat: 마이페이지 화면
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  data/src/main/java/com/paykidscompose/data/model/AuthStatusManagerImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/AuthRepositoryImpl.kt
  data/src/main/java/com/paykidscompose/data/repositories/UserRepositoryImpl.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
Labels: feature, refactor, fix

#125 feat: nav animation
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
Labels: feature

#128 refactor: 로그인 닉네임 화면 뷰모델 수정
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNicknameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNicknameViewModel.kt
Labels: feature, refactor

#131 refactor: 추상 클래스보다 인터페이스로 해야할 거 같아서 수정했습니다.
  common/src/main/java/com/paykidscompose/common/model/AuthStatusManager.kt
  data/src/main/java/com/paykidscompose/data/model/AuthStatusManagerImpl.kt
Labels: refactor

#134 refactor: HomeScreen 스테이지 해금 갱신 문제 해결
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeViewModel.kt
Labels: refactor
