Repository PayKids-Compose/paykids-android-compose, pull requests merged in 2025-06, with the labels that each got.

#10 res: 타이포그라피, 컬러 정의
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Theme.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Type.kt
Labels: design

#17 res: strings 정의
  presentation/src/main/res/values/strings.xml
Labels: res

#23 refactor: NickNameScreen
  presentation/src/main/java/com/paykidscompose/presentation/model/UIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/UserProfileUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNickNameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
Labels: refactor

#26 feat: HomeScreen 중첩 스크롤 임시 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/util/StageVisualUtil.kt
  presentation/src/main/res/drawable/bg_home_2.png
  presentation/src/main/res/drawable/bg_home_svg.xml
Labels: feature

#27 feat: 기본 마이페이지 구현
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/LoginScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/AppTopBarComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/ButtonComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/CardComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#30 feat: 약관 및 정책 화면 구현
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/terms/TermsPolicyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/CardComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#31 feat: 팝업 다이얼로그, UIModel을 사용하여 상태를 줄이고 각 화면 단위로 수정했습니다.
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyUser.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/MyInfoUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/MyPageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/UIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/UserProfileUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/LoginScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNickNameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DialogComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/util/PopupType.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
Labels: feature

#36 feat: 용돈일기 메인 화면 구현
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  presentation/src/main/java/com/paykidscompose/presentation/dummy/CalendarRepository.kt
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyCalendar.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/AllowanceDiaryUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/AllowanceType.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/java/com/paykidscompose/presentation/util/MoneyUtils.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#35 feat: 퀴즈 진입 화면 구현
  app/build.gradle.kts
  data/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizType.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/nickname/LoginNickNameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizEntryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/AppTopBarComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/ButtonComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DialogComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/util/PopupType.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/java/com/paykidscompose/presentation/util/StageVisualUtil.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#37 res: TextStyle 오류 수정
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
Labels: res

#39 refactor: 인풋필드 컴포넌트 수정함에 따라 내정보화면도 수정했습니다.
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
Labels: refactor

#43 feat: 카테고리 상세내역 화면 구현했습니다.
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
  presentation/src/main/java/com/paykidscompose/presentation/util/FormatUtils.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#45 refactor: PayKidsScaffold 컴포저블을 추가했습니다.
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/PayKidsScaffold.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/ScaffoldContainer.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/terms/TermsPolicyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/AppTopBarComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor

#47 feat: 퀴즈 클리어 화면 구현
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizClearConfig.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizClearType.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizClearScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/ShortAnswerQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/CardComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Font.kt
Labels: feature

#50 feat: 내비게이션 추가
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/AppRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/TabNavGraph.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/bottom/BottomBarItem.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/AllowanceDiaryNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/EntryNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/MyPageNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/QuizNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/TabNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/EntryPoint.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/bottom/BottomAppBarItem.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizClearScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizEntryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/AppBottomBarComponents.kt
  presentation/src/main/res/drawable/ic_quest_tab.xml
Labels: feature

#52 refactor: 모델 패키지에 enum들을 type 패키지로 이동
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  presentation/src/main/java/com/paykidscompose/presentation/dummy/CalendarRepository.kt
  presentation/src/main/java/com/paykidscompose/presentation/dummy/DummyCalendar.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/AllowanceDiaryUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizClearConfig.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/type/AllowanceType.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/type/QuizClearType.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/type/QuizType.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/home/HomeScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/login/LoginScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/terms/TermsPolicyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizClearScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/ShortAnswerQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DialogComponents.kt
Labels: refactor

#54 refactor: 내비게이션에 학습스크린 추가 및 화면 이동 가능하도록 수정
  presentation/src/main/java/com/paykidscompose/presentation/navigation/TabNavGraph.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/QuizNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizEntryScreen.kt
Labels: refactor
