Repository PayKids-Compose/paykids-android-compose, pull requests merged in 2025-08, with the labels that each got.

#136 refactor: GetAllQuizzesUseCase 수정
  app/src/main/java/com/paykidscompose/app/di/ApplicationContainerImpl.kt
  common/src/main/java/com/paykidscompose/common/usecase/quiz/GetAllQuizzesUseCase.kt
Labels: refactor

#138 feat: 에러 다이얼로그 추가 (로드 실패시 띄워주세요)
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DialogComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/util/PopupType.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#139 refactor: 용돈일기 관련 화면에서 쓰이는 다이얼로그를 수정했습니다. 내역 추가 및 수정 가능합니다.
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  app/src/main/java/com/paykidscompose/app/di/ApplicationContainerImpl.kt
  common/src/main/java/com/paykidscompose/common/di/ApplicationContainer.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/AllowanceDiaryViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/allowance/AllowanceDiaryUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/AllowanceDiaryViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/ExpenseAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/DialogComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/RelatedAllowanceComponents.kt
Labels: feature, refactor

#140 refactor: 매퍼 파일 이동
  presentation/src/main/java/com/paykidscompose/presentation/mapper/my/MyInfoUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/mapper/my/MyPageUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/MyInfoUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/MyPageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/info/MyInfoViewModel.kt
Labels: refactor

#142 refactor: 화면이 작은 휴대폰에서 보기 불편함이 있을 수 있기 때문에 스크롤 가능하도록 수정했습니다.
  presentation/src/main/java/com/paykidscompose/presentation/screens/mypage/MyPageScreen.kt
Labels: feature, refactor

#145 refactor: 지출 분석 화면 수정
  app/src/main/java/com/paykidscompose/app/MainActivity.kt
  app/src/main/java/com/paykidscompose/app/di/ApplicationContainerImpl.kt
  common/src/main/java/com/paykidscompose/common/di/ApplicationContainer.kt
  common/src/main/java/com/paykidscompose/common/usecase/allowance/expense/SaveExpenseCategoryUseCase.kt
  common/src/main/java/com/paykidscompose/common/usecase/allowance/income/SaveIncomeCategoryUseCase.kt
  data/src/main/java/com/paykidscompose/data/mapper/allowance/AllowanceChartCategoryMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/factory/TransactionAnalysisViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/allowance/CategoryProgressBarUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/allowance/TransactionAnalysisUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/TransactionAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/TransactionAnalysisViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/util/ColorUtil.kt
  presentation/src/main/res/values/strings.xml
Labels: feature, refactor, fix

#146 refactor: 퀴즈, 학습하기 관련 패키지 생성 및 파일 이동
  presentation/src/main/java/com/paykidscompose/presentation/factory/QuizEntryViewModelFactory.kt
  presentation/src/main/java/com/paykidscompose/presentation/mapper/quiz/QuizClearedUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/mapper/quiz/QuizUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/mapper/study/ChatMessageUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/ChatMessageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/QuizClearedUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/quiz/QuizClearConfigUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/quiz/QuizClearedUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/quiz/QuizUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/study/ChatMessageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/QuizViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/clear/QuizClearScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/entry/QuizEntryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/quiz/entry/QuizEntryViewModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screens/study/StudyScreen.kt
Labels: refactor

#147 refactor: 지출분석화면에서 기타 카테고리는 삭제하면 안돼서 삭제하기 모드에서 터치 안되도록 수정했습니다.
  presentation/src/main/java/com/paykidscompose/presentation/screens/allowance/analysis/TransactionAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
  presentation/src/main/res/values/strings.xml
Labels: feature, refactor

#163 docs: README 파일 수정 했습니다.
  README.md
Labels: documentation

#165 refactor: 카테고리 상세내역 화면에서 토스트 문제가 있어서 수정한 버전으로 README 업데이트 했습니다.
  README.md
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/detail/CategoryDetailViewModel.kt
Labels: documentation

#166 refactor: 미해금 스테이지 클릭
  presentation/src/main/java/com/paykidscompose/presentation/screen/home/HomeScreen.kt
Labels: refactor

#170 refactor: QuizViewModel collect -> collectLatest 변경
  presentation/src/main/java/com/paykidscompose/presentation/screen/quiz/QuizViewModel.kt
Labels: refactor

#177 feat: 퀴즈 클리어 화면 오답노트 풀기 버튼 구현
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/navigation/route/QuizNavigationRoute.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/quiz/clear/QuizClearScreen.kt
Labels: feature

#178 fix: 홈 화면 스테이지 클릭 시 발생하는 스테이지 정보 갱신 오류 해결
  presentation/src/main/java/com/paykidscompose/presentation/screen/home/HomeScreen.kt
Labels: fix

#180 refactor: 화면에서 플로우 수집할 때 그냥 수집하지 않기
  presentation/src/main/java/com/paykidscompose/presentation/navigation/PayKidsApp.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/analysis/TransactionAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/login/nickname/LoginNicknameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/mypage/info/MyInfoScreen.kt
Labels: refactor

#181 feat: AndroidManifest profileable 추가
  app/src/main/AndroidManifest.xml
Labels: feature

#182 refactor: 스플래시 액티비티에서 runBlocking 사용하는 코드 대신 async를 사용한 코드로 수정했습니다.
  app/src/main/java/com/paykidscompose/app/SplashActivity.kt
Labels: refactor

#183 refactor: 학습하기 화면 GPT 응답 대기 애니메이션 처리
  presentation/src/main/java/com/paykidscompose/presentation/mapper/study/ChatMessageUIModelMapper.kt
  presentation/src/main/java/com/paykidscompose/presentation/model/study/ChatMessageUIModel.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/study/StudyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/study/StudyViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature, refactor

#184 feat: hilt 관련 라이브러리 의존성 추가.
  app/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  data/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: feature

#187 refactor: 기술 스택 표에서 DI 수동 주입 빼고 Hilt로 수정했습니다.
  README.md
Labels: refactor

#189 refactor: hiltViewModel
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/AllowanceDiaryScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/analysis/TransactionAnalysisScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/allowance/detail/CategoryDetailScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/login/nickname/LoginNicknameScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/mypage/info/MyInfoScreen.kt
Labels: refactor

#192 feat: 퀴즈 bgm 및 효과음 추가
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/paykidscompose/presentation/audio/AudioHelper.kt
  presentation/src/main/java/com/paykidscompose/presentation/audio/AudioManager.kt
  presentation/src/main/java/com/paykidscompose/presentation/audio/SoundEffect.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/quiz/QuizScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/quiz/clear/QuizClearScreen.kt
  presentation/src/main/res/raw/quiz_bgm.mp3
  presentation/src/main/res/raw/quiz_clear_effect.mp3
  presentation/src/main/res/raw/quiz_correct_effect.mp3
  presentation/src/main/res/raw/quiz_fail_effect.mp3
  presentation/src/main/res/raw/quiz_wrong_effect.mp3
Labels: feature

#194 refactor: OutLineInputField 컴포넌트 텍스트 중앙 배치 가능하도록 개선
  presentation/src/main/java/com/paykidscompose/presentation/screen/mypage/info/MyInfoScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/quiz/section/ShortAnswerQuizContent.kt
  presentation/src/main/java/com/paykidscompose/presentation/screen/study/StudyScreen.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/components/TextComponents.kt
  presentation/src/main/java/com/paykidscompose/presentation/ui/theme/Dimens.kt
Labels: refactor, chore
